# Generated by Django 3.2.7 on 2021-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='employee_email',
            field=models.EmailField(max_length=256),
        ),
    ]
